### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by danieldraper** [stimulus-components/stimulus-checkbox-select-all#15]
Have you considered raising custom events.

This could then be used to hide/show bulk actions in the UI.

![CleanShot 2021-05-15 at 11 28 17](https://user-images.githubusercontent.com/1016423/118344277-c326da00-b570-11eb-9142-e6f503e9833a.gif)

**Comment by guillaumebriday** [comment]
Sorry for the late reply!

We already dispatch an input event when a checkbox is clicked. Isn't that enough for what you need to do?
