### ISSUE TITLE
Override refresh method

### ISSUE THREAD

**Issue by xama** [stimulus-components/stimulus-checkbox-select-all#16]
Hello, 
I need some help to override the refresh method, so the checkboxAll stay checked until i have all the checkboxs uncheked. 
so just like you mentionned in the doc, I created a new controller who extends the checkboxSelectAll, and the refresh method width super.refresh(), but when I try to modify this.checkboxAllTarget.indeterminate I got an error says  that I have a missing target element checkboxAll

`import CheckboxSelectAll from "stimulus-checkbox-select-all"

export default class extends CheckboxSelectAll {
  refresh(e) {
        super.refresh()
        this.checkboxAllTarget.indeterminate = checkboxesCheckedCount === 0
    }
}`

thank you for your help

**Comment by guillaumebriday** [comment]
Did you manage to use the controller without override it? Can you show me your html?
