### ISSUE TITLE
Support for invert

### ISSUE THREAD

**Issue by henkesn** [stimulus-components/stimulus-checkbox-select-all#18]
Hi guys,

thanks for your project. I have created a controller extending stimulus-checkbox-select-all which adds an invert method:

```typescript
    invert(e: Event): void {
        e.preventDefault();

        this.checkboxTargets.forEach(checkbox => {
            checkbox.checked = !checkbox.checked
            this.triggerInputEvent(checkbox)
        });
        this.refresh();
    }
```
This one can be used as stimulus action, e. g. 
```html
<button data-action="checkbox-select-all#invert">invert</button>
```

Do you think that could be a standard feature? I can provide a PR if you like.

**Comment by guillaumebriday** [comment]
That works great! But before merging it to the project I need to see if people want that feature which I think it could be marginal. Let's see in the future.

For now, I suggest you to keep your controller that extends stimulus-checkbox-select-all 👌
