### ISSUE TITLE
How to only select objects in a group

### ISSUE THREAD

**Issue by butzhang** [stimulus-components/stimulus-checkbox-select-all#21]
Let's say I have a group model which has_many person. In a form, I want to select all the person inside that group instead of everyone. I don't think currently this component support this use case. But it would be really helpful if it can extends to it. Thanks!

**Comment by guillaumebriday** [comment]
You'll need to override this line https://github.com/stimulus-components/stimulus-checkbox-select-all/blob/master/src/index.ts#L35 when extending the controller to add your specific condition I guess

Not sure it's a good idea to add that feature in the lib though 👍
