### ISSUE TITLE
Disabled checkboxes are checked

### ISSUE THREAD

**Issue by adrienpoly** [stimulus-components/stimulus-checkbox-select-all#9]
Ran into a little edge case where within the list of checkboxes,  some of them are disabled (locked features by examples).
Current behavior is that it will check all including the disabled checkboxes.
I think it shouldn't check them.
can make a PR for that if needed

**Comment by guillaumebriday** [comment]
Ah! I will check it out today, thanks @adrienpoly

**Comment by guillaumebriday** [comment]
Could you review the PR @adrienpoly?

**Comment by guillaumebriday** [comment]
Moved to https://github.com/stimulus-components/stimulus-components/issues/110
